            ;var jg=function jg(a){switch(arguments.length){case 1:return jg.g(arguments[0]);case 2:return jg.h(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return jg.H(arguments[0],arguments[1],2<c.length?new Zb(c.slice(2),0,null):null)}};jg.g=function(a){return-a};jg.h=function(a,b){return a-b};jg.H=function(a,b,c){return Yc(jg,a-b,c)};jg.W=function(a){var b=Q(a),c=S(a);a=Q(c);c=S(c);return this.H(b,a,c)};jg.V=2;var kg={};
function lg(a){a=a.currentTarget.closest(".collapse[gallery-season-key]");for(var b=P(xc(document.querySelectorAll(".collapse[gallery-season-key]"))),c=null,d=0,e=0;;)if(e<d){var f=c.J(null,e);cc.h(f,a)||f.classList.remove("collapse-open");e+=1}else if(b=P(b))c=b,Rc(c)?(b=Bb(c),e=Cb(c),c=b,d=X(b),b=e):(b=Q(c),cc.h(b,a)||b.classList.remove("collapse-open"),b=S(c),c=null,d=0),e=0;else break;return a.classList.toggle("collapse-open")}
function mg(){for(var a=P(xc(document.querySelectorAll(".collapse-title"))),b=null,c=0,d=0;;)if(d<c)b.J(null,d).addEventListener("click",lg),d+=1;else if(a=P(a))b=a,Rc(b)?(a=Bb(b),d=Cb(b),b=a,c=X(a),a=d):(Q(b).addEventListener("click",lg),a=S(b),b=null,c=0),d=0;else break;a=(new URLSearchParams(location.search)).get("season");return z(a)?(a=document.querySelector(['.collapse[gallery-season-key\x3d"',I.g(a),'"]'].join("")),z(a)?a.classList.add("collapse-open"):null):null}
da("gallery.collapse.init",function(){return mg()});mg();var ng={};if(typeof kg==="undefined"||typeof ng==="undefined"||typeof og==="undefined")var og=new yd(null);function pg(a,b,c){var d=document.getElementById("gallery-modal-iframe");d.src=a;d.title=b;document.getElementById("gallery-modal-description").textContent=b;a=(new Date(c)).toLocaleDateString(navigator.language,{day:"numeric",month:"long",year:"numeric"});return document.getElementById("gallery-modal-date").textContent=a}
function qg(a){if(cc.h(a,cb(og)))return null;var b=window.GALLERY_DATA[a];zd(og,a);pg(b.src,b.description,b.date);return document.getElementById("gallery-modal").classList.remove("hidden")}function rg(a){a.stopPropagation();a=document.getElementById("gallery-modal");return z(a)?(a.classList.add("hidden"),zd(og,null),pg(null,null,null)):null}function sg(a){a.stopPropagation();return qg(parseInt(a.currentTarget.getAttribute("gallery-idx")))}
function tg(a){a.stopPropagation();a=cb(og)-1;return qg(0>a?0:a)}if(typeof kg==="undefined"||typeof ng==="undefined"||typeof ug==="undefined")var ug=window.GALLERY_DATA_MAX_IDX;function vg(a){a.stopPropagation();a=cb(og)+1;return qg(ug<a?ug:a)}function wg(a,b){a=document.getElementById(a);z(a)&&a.addEventListener("click",b)}function xg(a){if(cb(og)!=null)switch(a.key){case "ArrowLeft":return tg(a);case "ArrowRight":return vg(a);case "Escape":return rg(a);default:return null}else return null}
if(typeof kg==="undefined"||typeof ng==="undefined"||typeof yg==="undefined")var yg=new yd(0);if(typeof kg==="undefined"||typeof ng==="undefined"||typeof zg==="undefined")var zg=new yd(0);if(typeof kg==="undefined"||typeof ng==="undefined"||typeof Ag==="undefined")var Ag=50;function Bg(a){var b=yg;a=jg.changedTouches.call(null,a)[0];a=jg.screenX.call(null,a);return zd(b,a)}
function Cg(a){var b=zg;var c=jg.changedTouches.call(null,a)[0];c=jg.screenX.call(null,c);zd(b,c);return cb(og)!=null?(b=cb(zg)-cb(yg),b>Ag?tg(a):b<-Ag?vg(a):null):null}
function Dg(){wg("gallery-modal",rg);wg("gallery-modal-future",tg);wg("gallery-modal-past",vg);for(var a=P(xc(document.querySelectorAll(".gallery-card"))),b=null,c=0,d=0;;)if(d<c)b.J(null,d).addEventListener("click",sg),d+=1;else if(a=P(a))b=a,Rc(b)?(a=Bb(b),d=Cb(b),b=a,c=X(a),a=d):(Q(b).addEventListener("click",sg),a=S(b),b=null,c=0),d=0;else break;document.addEventListener("keydown",xg);document.addEventListener("touchstart",Bg);return document.addEventListener("touchstart",Cg)}
da("gallery.modal.init",function(){return Dg()});Dg();