            ;function Eg(){}function Fg(){}function Gg(a){return a==null?!1:a!=null?a.m&8||u===a.Zb?!0:a.m?!1:B(Eg,a):B(Eg,a)}function Hg(a){a:for(var b=a;;)if(b=P(b))b=S(b);else break a;return a}function Ig(a,b,c,d){a=a.g?a.g(b):a.call(null,b);c=Yc(a,c,d);return a.g?a.g(c):a.call(null,c)}
function Jg(a,b,c){if(a!=null&&(a.B&4||u===a.Bb)){var d=Mc(a);return Ig(b,function(){function e(h){return fb(yb(h),d)}var f=null;f=function(h,k){switch(arguments.length){case 1:return e.call(this,h);case 2:return xb(h,k)}throw Error("Invalid arity: "+arguments.length);};f.g=e;f.h=function(h,k){return xb(h,k)};return f}(),wb(a),c)}return Ig(b,yc,a,c)}function Kg(a){return Yc(function(b,c){b.push(c);return b},[],a)}
function Lg(a){if(a!=null&&(a.m&64||u===a.Ta))if(S(a)){a:{var b=[];for(a=P(a);;)if(a!=null)b.push(Q(a)),a=S(a);else break a;b=void 0}b=Fc(b)}else b=P(a)?Q(a):wd;else b=a;return b}var Mg=function Mg(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Mg.H(0<c.length?new Zb(c.slice(0),0,null):null)};
Mg.H=function(a){var b=a instanceof Zb&&a.s===0?a.i:Kg(a);a=b.length;if(!Vc(a))throw Error(["Argument must be an integer: ",I.g(a)].join(""));if((a&1)!==0){a=Error;var c=I,d=c.g;a:{for(;;){var e=S(b);if(e!=null)b=e;else{b=Q(b);break a}}b=void 0}throw a(["No value supplied for key: ",d.call(c,b)].join(""));}return Fc(b)};Mg.V=0;Mg.W=function(a){return this.H(P(a))};function Ng(a,b){return yb(Yc(function(c,d){d=a.g?a.g(d):a.call(null,d);return xb(c,d)},wb(zc),b))}
var Og=function Og(a){switch(arguments.length){case 2:return Og.h(arguments[0],arguments[1]);case 3:return Og.l(arguments[0],arguments[1],arguments[2]);case 4:return Og.G(arguments[0],arguments[1],arguments[2],arguments[3]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Og.H(arguments[0],arguments[1],arguments[2],arguments[3],4<c.length?new Zb(c.slice(4),0,null):null)}};
Og.h=function(a,b){if(a instanceof yd){var c=a.state;b=b.g?b.g(c):b.call(null,c);a=zd(a,b)}else a=Eb.h(a,b);return a};Og.l=function(a,b,c){if(a instanceof yd){var d=a.state;b=b.h?b.h(d,c):b.call(null,d,c);a=zd(a,b)}else a=Eb.l(a,b,c);return a};Og.G=function(a,b,c,d){if(a instanceof yd){var e=a.state;b=b.l?b.l(e,c,d):b.call(null,e,c,d);a=zd(a,b)}else a=Eb.G(a,b,c,d);return a};
Og.H=function(a,b,c,d,e){if(a instanceof yd){var f=a.state;b.W?(c=wc(f,wc(c,wc(d,e))),d=b.V,e=3+Ic(d-2,e),b=e<=d?Jc(b,e,c):b.W(c)):b=td(b,f,c,d,P(e));a=zd(a,b)}else a=Eb.T(a,b,c,d,e);return a};Og.W=function(a){var b=Q(a),c=S(a);a=Q(c);var d=S(c);c=Q(d);var e=S(d);d=Q(e);e=S(e);return this.H(b,a,c,d,e)};Og.V=4;function Pg(){}
function Qg(a){if(a!=null&&a.Fb!=null)a=a.Fb(a);else{var b=Qg[r(a==null?null:a)];if(b!=null)a=b.g?b.g(a):b.call(null,a);else if(b=Qg._,b!=null)a=b.g?b.g(a):b.call(null,a);else throw G("IEncodeJS.-clj-\x3ejs",a);}return a}
function Rg(a,b){if(a!=null?u===a.Eb||(a.wb?0:B(Pg,a)):B(Pg,a))a=Qg(a);else if(typeof a==="string"||typeof a==="number"||a instanceof O||a instanceof Vb)a=b.g?b.g(a):b.call(null,a);else{var c=xc([a]);a=xa();c==null?b=!0:(c!=null?c.m&2||u===c.sb||(c.m?0:B(Ia,c)):B(Ia,c))?b=Ja(c)===0:(b=P(c),b=b==null?!0:b===!1?!0:!1);if(b)a="";else{b=I;var d=b.g,e=new na,f=new Ib(e);Oe(Q(c),f,a);c=P(S(c));for(var h=null,k=0,l=0;;)if(l<k){var m=h.J(null,l);sb(f," ");Oe(m,f,a);l+=1}else if(c=P(c))h=c,Rc(h)?(c=Bb(h),
k=Cb(h),h=c,m=X(c),c=k,k=m):(m=Q(h),sb(f," "),Oe(m,f,a),c=S(h),h=null,k=0),l=0;else break;a=d.call(b,e)}}return a}var Sg=function Sg(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Sg.H(arguments[0],1<c.length?new Zb(c.slice(1),0,null):null)};
Sg.H=function(a,b){b=Lg(b);var c=Xb(b,uf,id),d=function h(f){if(f==null)return null;if(f!=null?u===f.Eb||(f.wb?0:B(Pg,f)):B(Pg,f))return Qg(f);if(f instanceof O)return c.g?c.g(f):c.call(null,f);if(f instanceof Vb)return I.g(f);if(Oc(f)){var k={};f=P(f);for(var l=null,m=0,n=0;;)if(n<m){var q=l.J(null,n),t=Dc(q,0),w=Dc(q,1);q=k;t=Rg(t,d);w=h(w);q[t]=w;n+=1}else if(f=P(f))Rc(f)?(m=Bb(f),f=Cb(f),l=m,m=X(m)):(l=Q(f),m=Dc(l,0),n=Dc(l,1),l=k,m=Rg(m,d),n=h(n),l[m]=n,f=S(f),l=null,m=0),n=0;else break;return k}if(Gg(f)){k=
[];f=P(Ad.h(h,f));l=null;for(n=m=0;;)if(n<m)q=l.J(null,n),k.push(q),n+=1;else if(f=P(f))l=f,Rc(l)?(f=Bb(l),n=Cb(l),l=f,m=X(f),f=n):(f=Q(l),k.push(f),f=S(l),l=null,m=0),n=0;else break;return k}return f};return d(a)};Sg.V=1;Sg.W=function(a){var b=Q(a);a=S(a);return this.H(b,a)};function Tg(){}
function Ug(a,b){if(a!=null&&a.Db!=null)a=a.Db(a,b);else{var c=Ug[r(a==null?null:a)];if(c!=null)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=Ug._,c!=null)a=c.h?c.h(a,b):c.call(null,a,b);else throw G("IEncodeClojure.-js-\x3eclj",a);}return a}
function Vg(a){var b=xc([bg,!0]),c=Lg(b);c=Wb(c,bg);var d=z(c)?hd:I;return function h(f){return(f!=null?u===f.$b||(f.wb?0:B(Tg,f)):B(Tg,f))?Ug(f,ud(Mg,b)):(f==null?0:f!=null?f.m&64||u===f.Ta||(f.m?0:B(Fg,f)):B(Fg,f))?Hg(Ad.h(h,f)):$d(f)?new Zd(h($a(f)),h(ab(f))):Gg(f)?Jg(Bc(f),Ad.g(h),f):Ea(f)?yb(Yc(function(k,l){l=h(l);return xb(k,l)},wb(zc),f)):(f==null?null:f.constructor)===Object?yb(Yc(function(k,l){var m=d.g?d.g(l):d.call(null,l);l=h(la.call(null,f,l));return zb(k,m,l)},wb(wd),ka.call(null,f))):
f}(a)}var Wg={},Xg={};function Yg(a,b,c,d){return new x(null,6,[Kf,b,ig,Ng(c,a),lf,d,If,d,eg,d,Xf,20],null)}function Zg(a){return new Nd(null,5,5,Qd,[Yg(a,"Goals",hf,"#eec900"),Yg(a,"Shots",zf,"#ff7300"),Yg(a,"Passes",xf,"#00bfff"),Yg(a,"Carries",hg,"#82ca9d"),Yg(a,"Takeaways",Gf,"#ff1493")],null)}if(typeof Wg==="undefined"||typeof Xg==="undefined"||typeof $g==="undefined")var $g=new yd(df);if(typeof Wg==="undefined"||typeof Xg==="undefined"||typeof ah==="undefined")var ah=Vg(window.GAME_STATS_DATA);
if(typeof Wg==="undefined"||typeof Xg==="undefined"||typeof bh==="undefined")var bh=Vg(window.CUMULATIVE_GAME_STATS_DATA);
var ch=new x(null,6,[af,!0,Of,!1,tf,new x(null,3,[pf,"index",Zf,"x",Sf,!0],null),yf,new x(null,2,[Hf,new x(null,2,[gf,.2,nf,!1],null),Tf,new x(null,6,[cg,"#ffffff",Yf,2,Df,3,fg,"#ffffff",Ef,3,Ff,8],null)],null),Lf,new x(null,2,[rf,new x(null,2,[Rf,"top",$e,new x(null,3,[Af,new x(null,1,[Bf,20],null),Jf,1,of,20],null)],null),dg,new x(null,5,[Jf,1,of,15,jf,10,ef,new x(null,1,[Bf,18],null),wf,new x(null,1,[Cf,function(a){a=a[0];if(z(a)){a=parseInt(a.dataIndex);var b=tc(cc.h(cb($g),df)?bh:ah,a);a=bf.g(b);
var c=ag.g(b);b=mf.g(b);return[I.g(a),": @",I.g(c),"\n",I.g(b)].join("")}return null}],null)],null)],null),vf,new x(null,2,[Wf,new x(null,4,[kf,new x(null,2,[ff,"rgba(128,128,128,0.20)",Nf,.5],null),$f,new x(null,3,[Qf,!0,qf,2,ff,"#696969"],null),Pf,new x(null,1,[Af,new x(null,1,[Bf,18],null)],null),Cf,new x(null,3,[Qf,!0,gg,"Game #",Af,new x(null,1,[Bf,20],null)],null)],null),Ye,new x(null,4,[Pf,new x(null,1,[Af,new x(null,1,[Bf,18],null)],null),kf,new x(null,2,[ff,"rgba(128,128,128,0.20)",Nf,.5],
null),$f,new x(null,3,[Qf,!0,qf,2,ff,"#696969"],null),Cf,new x(null,3,[Qf,!0,gg,"Count",Af,new x(null,1,[Bf,20],null)],null)],null)],null)],null);function dh(a){Og.h($g,function(c){return cc.h(c,df)?Ze:df});var b=cc.h(cb($g),df)?bh:ah;a.data.labels=Sg(Ng(Uf,b));a.data.datasets=Sg(Zg(b));a.update.call(a);a.update();a=document.getElementById("toggle-game-graph");b=cc.h(cb($g),df)?"Show per-game":"Show cumulative";return a.textContent=b}
function eh(){var a=document.getElementById("game-graph").getContext("2d"),b=Sg(new x(null,3,[sf,"line",ig,new x(null,2,[$e,Ng(Uf,bh),cf,Zg(bh)],null),Vf,ch],null));return new Chart(a,b)}function fh(){var a=eh(),b=document.getElementById("toggle-game-graph");return z(b)?b.addEventListener("click",function(){return dh(a)}):null}da("landing.game_graph.init",fh);fh();