            ;function Ag(){}function Bg(){}function Cg(a){return a==null?!1:a!=null?a.m&8||t===a.Zb?!0:a.m?!1:B(Ag,a):B(Ag,a)}function Dg(a){a:for(var b=a;;)if(b=P(b))b=S(b);else break a;return a}function Eg(a,b,c,d){a=a.g?a.g(b):a.call(null,b);c=Yc(a,c,d);return a.g?a.g(c):a.call(null,c)}
function Fg(a,b,c){if(a!=null&&(a.B&4||t===a.Bb)){var d=Mc(a);return Eg(b,function(){function e(h){return fb(yb(h),d)}var f=null;f=function(h,k){switch(arguments.length){case 1:return e.call(this,h);case 2:return xb(h,k)}throw Error("Invalid arity: "+arguments.length);};f.g=e;f.h=function(h,k){return xb(h,k)};return f}(),wb(a),c)}return Eg(b,yc,a,c)}function Gg(a){return Yc(function(b,c){b.push(c);return b},[],a)}
function Hg(a){if(a!=null&&(a.m&64||t===a.Ta))if(S(a)){a:{var b=[];for(a=P(a);;)if(a!=null)b.push(R(a)),a=S(a);else break a;b=void 0}b=Fc(b)}else b=P(a)?R(a):wd;else b=a;return b}var Ig=function Ig(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Ig.I(0<c.length?new Zb(c.slice(0),0,null):null)};
Ig.I=function(a){var b=a instanceof Zb&&a.s===0?a.i:Gg(a);a=b.length;if(!Vc(a))throw Error(["Argument must be an integer: ",H.g(a)].join(""));if((a&1)!==0){a=Error;var c=H,d=c.g;a:{for(;;){var e=S(b);if(e!=null)b=e;else{b=R(b);break a}}b=void 0}throw a(["No value supplied for key: ",d.call(c,b)].join(""));}return Fc(b)};Ig.V=0;Ig.aa=function(a){return this.I(P(a))};function Jg(a,b){return yb(Yc(function(c,d){d=a.g?a.g(d):a.call(null,d);return xb(c,d)},wb(zc),b))}
var Kg=function Kg(a){switch(arguments.length){case 2:return Kg.h(arguments[0],arguments[1]);case 3:return Kg.l(arguments[0],arguments[1],arguments[2]);case 4:return Kg.G(arguments[0],arguments[1],arguments[2],arguments[3]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Kg.I(arguments[0],arguments[1],arguments[2],arguments[3],4<c.length?new Zb(c.slice(4),0,null):null)}};
Kg.h=function(a,b){if(a instanceof yd){var c=a.state;b=b.g?b.g(c):b.call(null,c);a=zd(a,b)}else a=Eb.h(a,b);return a};Kg.l=function(a,b,c){if(a instanceof yd){var d=a.state;b=b.h?b.h(d,c):b.call(null,d,c);a=zd(a,b)}else a=Eb.l(a,b,c);return a};Kg.G=function(a,b,c,d){if(a instanceof yd){var e=a.state;b=b.l?b.l(e,c,d):b.call(null,e,c,d);a=zd(a,b)}else a=Eb.G(a,b,c,d);return a};
Kg.I=function(a,b,c,d,e){if(a instanceof yd){var f=a.state;b.aa?(c=wc(f,wc(c,wc(d,e))),d=b.V,e=3+Ic(d-2,e),b=e<=d?Jc(b,e,c):b.aa(c)):b=td(b,f,c,d,P(e));a=zd(a,b)}else a=Eb.T(a,b,c,d,e);return a};Kg.aa=function(a){var b=R(a),c=S(a);a=R(c);var d=S(c);c=R(d);var e=S(d);d=R(e);e=S(e);return this.I(b,a,c,d,e)};Kg.V=4;function Lg(){}
function Mg(a){if(a!=null&&a.Fb!=null)a=a.Fb(a);else{var b=Mg[r(a==null?null:a)];if(b!=null)a=b.g?b.g(a):b.call(null,a);else if(b=Mg._,b!=null)a=b.g?b.g(a):b.call(null,a);else throw G("IEncodeJS.-clj-\x3ejs",a);}return a}
function Ng(a,b){if(a!=null?t===a.Eb||(a.wb?0:B(Lg,a)):B(Lg,a))a=Mg(a);else if(typeof a==="string"||typeof a==="number"||a instanceof O||a instanceof Vb)a=b.g?b.g(a):b.call(null,a);else{var c=xc([a]);a=xa();c==null?b=!0:(c!=null?c.m&2||t===c.sb||(c.m?0:B(Ia,c)):B(Ia,c))?b=Ja(c)===0:(b=P(c),b=b==null?!0:b===!1?!0:!1);if(b)a="";else{b=H;var d=b.g,e=new oa,f=new Jb(e);Oe(R(c),f,a);c=P(S(c));for(var h=null,k=0,l=0;;)if(l<k){var m=h.J(null,l);sb(f," ");Oe(m,f,a);l+=1}else if(c=P(c))h=c,Rc(h)?(c=Bb(h),
k=Cb(h),h=c,m=X(c),c=k,k=m):(m=R(h),sb(f," "),Oe(m,f,a),c=S(h),h=null,k=0),l=0;else break;a=d.call(b,e)}}return a}var Og=function Og(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Og.I(arguments[0],1<c.length?new Zb(c.slice(1),0,null):null)};
Og.I=function(a,b){b=Hg(b);var c=Xb(b,vf,id),d=function h(f){if(f==null)return null;if(f!=null?t===f.Eb||(f.wb?0:B(Lg,f)):B(Lg,f))return Mg(f);if(f instanceof O)return c.g?c.g(f):c.call(null,f);if(f instanceof Vb)return H.g(f);if(Oc(f)){var k={};f=P(f);for(var l=null,m=0,n=0;;)if(n<m){var q=l.J(null,n),u=Dc(q,0),w=Dc(q,1);q=k;u=Ng(u,d);w=h(w);q[u]=w;n+=1}else if(f=P(f))Rc(f)?(m=Bb(f),f=Cb(f),l=m,m=X(m)):(l=R(f),m=Dc(l,0),n=Dc(l,1),l=k,m=Ng(m,d),n=h(n),l[m]=n,f=S(f),l=null,m=0),n=0;else break;return k}if(Cg(f)){k=
[];f=P(Ad.h(h,f));l=null;for(n=m=0;;)if(n<m)q=l.J(null,n),k.push(q),n+=1;else if(f=P(f))l=f,Rc(l)?(f=Bb(l),n=Cb(l),l=f,m=X(f),f=n):(f=R(l),k.push(f),f=S(l),l=null,m=0),n=0;else break;return k}return f};return d(a)};Og.V=1;Og.aa=function(a){var b=R(a);a=S(a);return this.I(b,a)};function Pg(){}
function Qg(a,b){if(a!=null&&a.Db!=null)a=a.Db(a,b);else{var c=Qg[r(a==null?null:a)];if(c!=null)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=Qg._,c!=null)a=c.h?c.h(a,b):c.call(null,a,b);else throw G("IEncodeClojure.-js-\x3eclj",a);}return a}
function Rg(a){var b=xc([cg,!0]),c=Hg(b);c=Wb(c,cg);var d=z(c)?hd:H;return function h(f){return(f!=null?t===f.$b||(f.wb?0:B(Pg,f)):B(Pg,f))?Qg(f,ud(Ig,b)):(f==null?0:f!=null?f.m&64||t===f.Ta||(f.m?0:B(Bg,f)):B(Bg,f))?Dg(Ad.h(h,f)):$d(f)?new Zd(h($a(f)),h(ab(f))):Cg(f)?Fg(Bc(f),Ad.g(h),f):Ea(f)?yb(Yc(function(k,l){l=h(l);return xb(k,l)},wb(zc),f)):(f==null?null:f.constructor)===Object?yb(Yc(function(k,l){var m=d.g?d.g(l):d.call(null,l);l=h(la.call(null,f,l));return zb(k,m,l)},wb(wd),ka.call(null,f))):
f}(a)}var Sg={};function Tg(a,b,c,d){return new x(null,6,[Mf,b,jg,Jg(c,a),mf,d,Kf,d,fg,d,Yf,20],null)}function Ug(a){return new Nd(null,6,5,Qd,[Tg(a,"Goals",jf,"#eec900"),Tg(a,"Apples",Ze,"#ff1493"),Tg(a,"Shots",Af,"#ff7300"),Tg(a,"Passes",yf,"#bc8f8f"),Tg(a,"Carries",ig,"#82ca9d"),Tg(a,"Takeaways",If,"#00bfff")],null)}
function Vg(a){return new x(null,4,[lf,new x(null,2,[gf,"rgba(128,128,128,0.20)",Of,.5],null),ag,new x(null,3,[Rf,!0,rf,2,gf,"#696969"],null),Qf,new x(null,1,[Bf,new x(null,1,[Cf,18],null)],null),Df,new x(null,3,[Rf,!0,hg,a,Bf,new x(null,1,[Cf,20],null)],null)],null)}
function Wg(){var a=Xg;return new x(null,6,[bf,!0,Pf,!1,uf,new x(null,3,[qf,"index",$f,"x",Tf,!0],null),zf,new x(null,2,[Jf,new x(null,2,[hf,.2,of,!1],null),Uf,new x(null,6,[dg,"#ffffff",Zf,2,Ff,3,gg,"#ffffff",Gf,3,Hf,8],null)],null),Nf,new x(null,2,[sf,new x(null,2,[Sf,"top",af,new x(null,3,[Bf,new x(null,1,[Cf,20],null),Lf,1,pf,20],null)],null),eg,new x(null,5,[Lf,1,pf,15,kf,10,ff,new x(null,1,[Cf,18],null),xf,new x(null,1,[Df,function(b){b=b[0];if(z(b)){var c=tc(a,parseInt(b.dataIndex));b=cf.g(c);
var d=bg.g(c);c=nf.g(c);b=[H.g(b)," @",H.g(d),"\n",H.g(c)].join("")}else b=null;return b}],null)],null)],null),wf,new x(null,2,[Xf,Vg("Game #"),Ye,Vg("Count")],null)],null)};var Yg={};if(typeof Sg==="undefined"||typeof Yg==="undefined"||typeof Zg==="undefined")var Zg=new yd(ef);if(typeof Sg==="undefined"||typeof Yg==="undefined"||typeof $g==="undefined")var $g=Rg(window.GAME_STATS_DATA);if(typeof Sg==="undefined"||typeof Yg==="undefined"||typeof Xg==="undefined")var Xg=Rg(window.CUMULATIVE_GAME_STATS_DATA);function ah(){var a=document.getElementById("toggle-game-graph"),b=cc.h(cb(Zg),ef)?"Show per-game":"Show cumulative";return a.textContent=b}
function bh(a){Kg.h(Zg,function(c){return cc.h(c,ef)?$e:ef});var b=cc.h(cb(Zg),ef)?Xg:$g;a.data.labels=Og(Jg(Vf,b));a.data.datasets=Og(Ug(b));a.update.call(a);a.update();return ah()}function ch(){var a=document.getElementById("game-graph").getContext("2d"),b=Og(new x(null,3,[tf,"line",jg,new x(null,2,[af,Jg(Vf,Xg),df,Ug(Xg)],null),Wf,Wg()],null));return new Chart(a,b)}function dh(){var a=ch();return kg("toggle-game-graph",function(){return bh(a)})}da("landing.game_graph.init",dh);dh();